# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

jobs:
- job: Windows
  displayName: Build on Windows

  pool:
    vmImage: vs2017-win2016

  variables:
    BuildConfiguration: Release

  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: ViewComponentsDemo.sln
      arguments: -c $(BuildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: Run Tests
    inputs:
      command: test
      projects: '**/*.Tests/*.csproj'
      arguments: -c $(BuildConfiguration) --no-build --logger "trx;LogFileName=TestResults.trx" --collect "Code coverage" -s $(System.DefaultWorkingDirectory)/CodeCoverage.runsettings

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: -c $(BuildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
