# define the expected parameters
parameters:
  operatingSystem: ''
  vmImage: ''

jobs:
- job: ${{parameters.operatingSystem}}
  displayName: Build on ${{parameters.operatingSystem}}

  pool:
    vmImage: ${{parameters.vmImage}}

  variables:
    BuildConfiguration: Release

  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: ViewComponentsDemo.sln
      arguments: -c $(BuildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*.Tests/*.csproj'
      arguments: -c $(BuildConfiguration) --no-build --collect "Code coverage" -s $(System.DefaultWorkingDirectory)/CodeCoverage.runsettings

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: -c $(BuildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
